### ISSUE TITLE
[FR] make plugin work with Custom Background

### ISSUE THREAD

**Issue by fnsign** [jneilliii/OctoPrint-PlotlyTempGraph#11]
Any chance to make it work with the Custom Background plugin?

**Comment by jneilliii** [comment]
I'll try.

**Comment by jneilliii** [comment]
Just released version 0.1.1rc1 that should in theory allow the custom background plugin to work. The only caveat is that you have no control of the same settings and it would be best to resize the image accordingly ahead of time. Change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted. if you want to try it out and verify.

**Comment by fnsign** [comment]
Thanks for the feedback and the new version!
I currently have a 10h print going on, so I'm looking forward testing it tomorrow.

**Comment by fnsign** [comment]
My current print broke, so I had the opportunity to test the new version.
It works! It took over my current custom background image without any changes.
Thanks again!
