### ISSUE TITLE
Is there a way to customize the tool name?

### ISSUE THREAD

**Issue by paul-tian** [jneilliii/OctoPrint-PlotlyTempGraph#12]
Hello jneilliii,

Is there a way to customize the tool name? Currently it shows "tool 0" etc. in the graph and would lead to a bit confusing.
It would be great if the "tool 0" could be customize to the name of presenting data source (e.g. "extruder" for "tool 0").

Thank you.

**Comment by jneilliii** [comment]
Right now I'm just using it as it's given to me from octoprint's side I think. It shouldn't be too difficult to have a name mapping overlay for the graph though.

**Comment by jneilliii** [comment]
Just released version 0.1.1rc3 that should in theory allow the customization of the label and color of the graph lines. Change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted. if you want to try it out and verify.
