### ISSUE TITLE
Seems to break your other plugin "Consolidate Temp Control"

### ISSUE THREAD

**Issue by Misterke** [jneilliii/OctoPrint-PlotlyTempGraph#13]
I used "Consolidate Temp Control" to combine the Control and Temp tabs, which worked fine, until I installed this PlotlyTempGraph.  It seems to force Control and Temp back into separate tabs ...

**Comment by jneilliii** [comment]
By the way, my Consolidated Tabs plugin would allow you to combine this plugin and the Control tab, or any other tab for that matter. Might be a good alternative?

**Comment by Misterke** [comment]
@jneilliii , I've installed the Consolidated Tabs plugin, but it isn't really the combining I was looking for.  I can't really put my finger on what it is, but it just doesn't ring my bell.  Maybe it's having to set the size of the temp tab manually to get things to fit, maybe it's just my weird taste ...  However, I have been getting used again to having them on separate tabs, so I'm happy enough.

Ah, and yes, the Consolidated Tabs plugin did seem to work with the PlotlyTempGraph, unlike the Consolidate Temp Control.  So,  that could indeed be a workaround for other people.

**Comment by jneilliii** [comment]
Ok, well I'll close this ticket then because consolidated tabs does work. In regard to sizing on that plugin's content, you only have to do it once and save and it's possible to get exactly the same results as the other plugin by enabling some of its settings (full width).
