### ISSUE TITLE
Save state of legend toggle.

### ISSUE THREAD

**Issue by technoplunk** [jneilliii/OctoPrint-PlotlyTempGraph#16]
Thanks for this new graph plugin I'm loving it already. It would be nice if one of the configuration options would be a toggle to "Always show legend". I prefer it on as I have a few extra sensors in my printer and its confusing without it. Everytime I reload the octoprint interface I have to turn it back on.

**Comment by jneilliii** [comment]
Nice idea. I will add that with the next release when I get around to it.

**Comment by jneilliii** [comment]
Rather than make it an option, it makes sense to me to just make the visibility state persistent. I've done that in the above commit and available as part of version 0.1.2rc1. You can switch the release channel for the plugin to `Release Candidate` in OctoPrint's software update settings.

**Comment by technoplunk** [comment]
This also works for me thanks!
