### ISSUE TITLE
Adding new temperatures or other parameters also in the list below the plot?

### ISSUE THREAD

**Issue by JLatasa** [jneilliii/OctoPrint-PlotlyTempGraph#19]
Hi. 
Congratulations on this fantastic contribution you are doing to OctoPrint! Good job mate!

I am not aware of the difficulty of my proposed task but in my case, it would be very useful if it was possible adding new temperatures or other parameters also in the list below the plot. 
It would be very useful to send customized g-code commands to control additional accessories in the printer environment, as it can be done with the temperatures.

**Comment by jneilliii** [comment]
What you describe sounds like [Custom Controls](https://plugins.octoprint.org/plugins/customControl/) or [Terminal Commands](https://plugins.octoprint.org/plugins/terminalcommandsextended/), but for this plugin's tab? I personally use consolidated tabs to merge multiple tabs together, and then custom controls show on the same page.
