### ISSUE TITLE
Graph not updating with UI Customizer

### ISSUE THREAD

**Issue by kfrancis** [jneilliii/OctoPrint-PlotlyTempGraph#23]
Love the plugin.

Since I installed [UI Customizer](https://plugins.octoprint.org/plugins/uicustomizer/), the graph doesn't update

**Comment by jneilliii** [comment]
Any errors in your developers tool's (F12) console tab? Don't know if @LazeMSS might know anything about this or not.

**Comment by jneilliii** [comment]
I just tested in my UI Customizer instance and the graph seems to be working. Will need more details.

**Comment by LazeMSS** [comment]
Also works on my development

**Comment by kfrancis** [comment]
Hmm, I'll see what I can gather. I didn't see any errors, just some warnings that looks relevant (about temp).

**Comment by kfrancis** [comment]
Using theme: Discorded

## Versions
* UI Customizer: v0.1.7.0
* Plotly: v0.1.2

Dev tools has messages like:
```
Did not bind view model TemperatureViewModel to target #temp since it does not exist
Did not bind view model TemperatureViewModel to target #temp_link since it does not exist
```
![2021-10-14 13_07_51-Predator OctoPrint  OctoPrint  and 5 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/67574/137364294-690ca9f9-f7b8-40a7-93d3-1213d47cd2ec.png)

**Comment by jneilliii** [comment]
Ah, this might be the temperature widget in UI Customizer interfering since my plugin replaces the default view model. I don't enable that in my instance. If you hide that in UI Customizer's settings does it work after refreshing the page?

**Comment by jneilliii** [comment]
@LazeMSS I think this could be relatively easy to fix using optional viewmodel dependency with this plugin's identifier, and redefining self.tempModel to use that parameter[index] if it exists. I'll do some testing when I get home tonight and submit a PR to UI Customizer if it works.

**Comment by jneilliii** [comment]
@kfrancis I couldn't message you via twitter. could you do a test for me and see if installing this version of the UICustomizer has any effect? OctoPrint settings > Plugin Manager > Get More > ...from URL.
```
https://github.com/jneilliii/OctoPrint-UICustomizer/archive/refs/heads/bugfix/plotlytempgraph.zip
```

**Comment by jneilliii** [comment]
I will say, even after enabling the temperature widget in UI Customizer the original version was still working for me, so this could potentially be a combination of multiple plugins causing this. I would be willing to connect to your instance to debug, just shoot me an email or reach out on the OctoPrint Discord server.

**Comment by LazeMSS** [comment]
No basically what you are doing is replacing the native temp model with plotlytempgraphViewModel if present - it looks nice and simple :)

**Comment by jneilliii** [comment]
PR submitted.
