### ISSUE TITLE
Chamber temp not appearing

### ISSUE THREAD

**Issue by anrienexe** [jneilliii/OctoPrint-PlotlyTempGraph#29]
Everything was working fine until I updated Octopi yesterday. I don't often update so I don't know which version I was but I am now on version 1.8.1.

Bed temp should be green:

![image](https://user-images.githubusercontent.com/73353175/170828194-0ae31708-f875-4d9c-bb20-44146a65446a.png)

Only tool + bed graph are shown :( :

![image](https://user-images.githubusercontent.com/73353175/170828223-6cf89ccf-ab6b-45fa-8282-abbf20e21bd7.png)

**Comment by jneilliii** [comment]
Need to see how the temperature is coming in from the terminal tab of octoprint

**Comment by anrienexe** [comment]
Is this what you are looking for?

```
#######################################
#### Enclosure Temp Sensor Section ####
#######################################
[thermistor chamber_temp]
temperature1: 25
resistance1: 10000
beta: 3950


[temperature_sensor enclosure_temp]
sensor_type: chamber_temp
sensor_pin: P0.23
min_temp: 0
max_temp: 100
gcode_id: C
```

**Comment by jneilliii** [comment]
Not much experience with klipper, but what I'm looking for is this bits from the Terminal tab from OctoPrint. That is how OP will give the information to the plugin to allow for processing properly. 

![image](https://user-images.githubusercontent.com/5249455/170849332-a3dfd4c9-6933-43dd-9ff7-0d5a1e278033.png)

**Comment by jneilliii** [comment]
I was able to reproduce the issue with 1.8.1 and virtual printer emulating with chamber temperature. I'm not quite sure why the plugin isn't picking up the temp now from the serial comms but suspect it does have something to do with changes to core OctoPrint. Will investigate further. 

![image](https://user-images.githubusercontent.com/5249455/170849473-7e11047d-7a80-443a-a146-5c02ef6948bc.png)

**Comment by jneilliii** [comment]
I think I remember the issue now after looking through old OctoPrint issues. You have to also enable the chamber in the printer profile.

![image](https://user-images.githubusercontent.com/5249455/170849775-c8bf8bdb-3b3a-4c02-a0ac-e2db5f453175.png)

With that option enabled then the virtual printer gets the data from OctoPrint and is able to graph.

![image](https://user-images.githubusercontent.com/5249455/170849817-44c5cf62-92cb-466c-b0f7-173c9fc0fff6.png)

**Comment by anrienexe** [comment]
Thanks for you speed light support! :)
