### ISSUE TITLE
MMU Data Causes Random New Temps

### ISSUE THREAD

**Issue by Cookietyrant** [jneilliii/OctoPrint-PlotlyTempGraph#30]
Plotly keeps adding duplicate entries that cannot be deleted until rebooted.
![Screenshot 2022-06-06 144812](https://user-images.githubusercontent.com/80727455/172236564-7c22e63a-6fdc-4167-bbf5-35f2e200b80a.jpg)

**Comment by jneilliii** [comment]
You have a MMU? The issue stems from the garbage being reported in the temperature report. If you look at the terminal tab you'll see what I'm talking about. Basically with octoprint 1.8.0 all those are being parsed as temperature data, when they shouldn't be. We were discussing this on octoprint discord just the other day.

**Comment by Cookietyrant** [comment]
Indeed I am running a MMU... Lol it's a bit annoying being it makes the graph nearly unreadable after a time...

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by jneilliii** [comment]
Yeah, discussion on discord seemed to indicate it might be possible to fix with single file plugin to filter out the BS that Prusa had added to the comm layer.

**Comment by jneilliii** [comment]
@Cookietyrant can you do me a favor and enable serial logging on your OctoPrint instance in settings > serial connection and let it run for a bit to gather those random lines from the printer, and then share your serial.log? This will help get a single file plugin fix implemented.

**Comment by Cookietyrant** [comment]
Most certainly I can do it when I get home tonight.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by jneilliii** [comment]
Thanks. You'll have to upload the file via GitHub web interface as email attachments don't come through. You should be able to just drag the file into a comment to upload.

**Comment by Cookietyrant** [comment]
Here is the Serial Log

[Uploading serial.log…]()

**Comment by Cookietyrant** [comment]
[serial.log](https://github.com/jneilliii/OctoPrint-PlotlyTempGraph/files/8874378/serial.log)

**Comment by jneilliii** [comment]
go into plugin manager, click get more, and copy/paste the url below into the from URL field and click install. once you restart I think the issue will be resolved. 

```
https://gist.github.com/jneilliii/6a2cbf0056e8c9e5ed5a828fa1694aad/raw/0bfa67bbc2f7cd543e3d83fce3cd60cdcfad1b00/prusa_temp_fix.py
```
