### ISSUE TITLE
Duplicate temperatures after printer resets

### ISSUE THREAD

**Issue by jmsaltzman** [jneilliii/OctoPrint-PlotlyTempGraph#31]
The plugin shows every line twice in the graph and legend. I think this is a result of multiple printer (Prusa MK3S) resets.

**Comment by jneilliii** [comment]
it graphs what ever is reported by your firmware. please provide screenshots with the legend open and your settings please.

**Comment by jmsaltzman** [comment]
Sorry I restarted the Pi and have not been able to replicate this.

**Comment by jneilliii** [comment]
Thanks for the update. I'll go ahead and close for now, if it comes back up please comment back on this issue.
