### ISSUE TITLE
Enhancement: Allow temperature recording to continue even when printer off/disconnected

### ISSUE THREAD

**Issue by puterboy** [jneilliii/OctoPrint-PlotlyTempGraph#34]
Would be great to allow temperatures to keep displaying even when printer disconnected for sensors that don't rely on the printer such as an enclosure temperature sensor or the RPi internal temperature.

In particular, I would like to see how my enclosure heats up/cools down even when printer is off.

Note that the plugin "Navbar Temperature Plugin" has such a feature.

Thanks!
(sorry for filing so many enhancements but take it as a compliment that I really find your plugin most useful!!!!!)

**Comment by jneilliii** [comment]
Unfortunately this is not possible because of the way this plugin interacts with OctoPrint's data stream of temperatures being graphed.
