### ISSUE TITLE
[BUG] Custom Background Image Scaling Issues

### ISSUE THREAD

**Issue by jneilliii** [jneilliii/OctoPrint-PlotlyTempGraph#35]
As discussed in https://github.com/jneilliii/OctoPrint-CustomBackground/issues/42 and https://github.com/jneilliii/OctoPrint-FloatingNavbar/issues/14 fill options don't work with Plotly, so need to make adjustments accordingly for the paper background.

**Comment by jneilliii** [comment]
@puterboy, latest [0.1.4rc7](https://github.com/jneilliii/OctoPrint-PlotlyTempGraph/releases/tag/0.1.4rc7) version should resolve the weird sizing of images.

**Comment by puterboy** [comment]
Thanks!
