### ISSUE TITLE
[BUG] Custom Background Axes/Text Color Options

### ISSUE THREAD

**Issue by jneilliii** [jneilliii/OctoPrint-PlotlyTempGraph#36]
When these options are set they are not coming through to graph, as mentioned in https://github.com/jneilliii/OctoPrint-CustomBackground/issues/43

**Comment by jneilliii** [comment]
@puterboy, latest [0.1.4rc7](https://github.com/jneilliii/OctoPrint-PlotlyTempGraph/releases/tag/0.1.4rc7) version should recognize custom background color settings and adjust the graph accordingly.

**Comment by puterboy** [comment]
Thanks!
