### ISSUE TITLE
Typo prevents tool target to show up in graph

### ISSUE THREAD

**Issue by a123qwertz567** [jneilliii/OctoPrint-PlotlyTempGraph#39]
I noticed that the tool target temperature was not showing up after installing the plugin.

The reason was a typo in the default configuration.

In the file "/octoprint_plotlytempgraph/__init__.py" in Line 29 the term "tool0 trget" has to be modified to "tool0 target". I did this change over the GUI of octorpint and everything worked.

Becasue I do not know how to work git to make an push reuqests or what ever I made this issue to inform about the fix.

**Comment by jneilliii** [comment]
I actually already have this fixed in the latest RC release and will go out with the next version.
