### ISSUE TITLE
Unneeded Tool graph for shared hotend

### ISSUE THREAD

**Issue by LMS0815** [jneilliii/OctoPrint-PlotlyTempGraph#4]
I have a printer with two extrudes but a shared hot end (tool). 
There is no need to provide/generate a second graph for a non existing tool.

![image](https://user-images.githubusercontent.com/8235214/100907656-df572300-34ca-11eb-80f4-3fe81bbc72c7.png)

![image](https://user-images.githubusercontent.com/8235214/100907978-3fe66000-34cb-11eb-8346-8e96958f18b1.png)

**Comment by jneilliii** [comment]
I've linked you to the rc4 version in the other two issues you opened. Could you let me know if those changes also fixed this issue or not?

**Comment by jneilliii** [comment]
@LMS0815 curious with your shared nozzle, does the temperature report the same for both tools all the time or is the second tool not graphed at all? It's a little hard to tell from the screenshot if they might be overlapped or not.

**Comment by LMS0815** [comment]
Both share the same temperature (more or less as there seems to be a small deviation). I have no idea where the data is coming from, as my Printer (Creality CR-X)  is only reporting one nozzle temperature.

**Comment by jneilliii** [comment]
Ok, thanks. I'll try to debug this using the virtual printer with a 2 nozzle shared setup and see how it acts.

**Comment by jneilliii** [comment]
@LMS0815 finally got around to working on this plugin actively again now that it's released and have resolved the issue with additional nozzles being graphed with the shared nozzle option enabled. Change the plugin's release channel in OctoPrint's Software Update settings to Release Candidate and upgrade to version 0.1.2rc2 when prompted. if you want to try it out and verify.
