### ISSUE TITLE
Display latest temperature when mouse over right edge of graph

### ISSUE THREAD

**Issue by jmsaltzman** [jneilliii/OctoPrint-PlotlyTempGraph#42]
It would be great to watch the values update in real time, but it's almost impossible to position the mouse left-right to show the latest time. Then when mousing over the area just to the right (but still inside the border), the labels go away :(  Thank you!

**Comment by jneilliii** [comment]
not sure what you mean, but if I hold the mouse over the end of the graph like in the below picture, it automatically updates for me as the temp changes and the timeline moves to the left. Also, you do know the current real-time temp is displayed just below it in the Actual column?

![image](https://user-images.githubusercontent.com/5249455/218218423-a803a62a-4066-4bb0-a96d-f50dfa86d66c.png)

**Comment by jneilliii** [comment]
I just realized what you mean, once the temp starts changing the closest line moves away from the mouse and therefore doesn't show the hover pop-up anymore. It seems I can fix this by applying a hovermode = x to the plotly library and anywhere you hover on the graph will show all the pop-ups at once. I'm going to implement this now and test, then push to rc branch. If you change the plugin's release channel in OctoPrint's Software Update settings to `release candidate` you will be notified when that update goes live.

**Comment by jmsaltzman** [comment]
Yes! Thank you! Mousing near the right black border to show all the curves, each with a little colored tag tracking the current value is just.. [chef kiss].
