### ISSUE TITLE
Logging Values from graph

### ISSUE THREAD

**Issue by Tkmax2000** [jneilliii/OctoPrint-PlotlyTempGraph#52]
Hi, I would like to know if there is a way to automatically log temperature values from the temperature graph. I know that we can get the temeprature values if hover above any point. What I want is to get a list of temperature values for a given time inrterval.

**Comment by jneilliii** [comment]
no not really possible in its current state and not something I'm looking to add. I would recommend you look into the [Prometheus Exporter](https://plugins.octoprint.org/plugins/prometheus_exporter/) plugin for long term data like that.
