### ISSUE TITLE
Cutoff value stopped working in 0.0.4rc5 

### ISSUE THREAD

**Issue by Dak0r** [jneilliii/OctoPrint-PlotlyTempGraph#9]
Hi, I'm currently using the 0.0.4rc5 release.

I noticed that the cutoff stopped working for me, if you leave Octoprint open, in this release:

I open Ocotoprints website, start a print and let it do its work. When I come back to the website later, I can see the whole graph (see image).

When I reload the page, the cutoff is correct for all existing values, but once new values come in, old ones do not get removed from the graph.

![plotly_cutoff](https://user-images.githubusercontent.com/4193623/106007126-4271ca00-60b6-11eb-9b0b-d18c13536c31.jpg)

**Comment by jneilliii** [comment]
Thanks I was noticing the same. I'm not quite sure why that's happening yet and haven't had time to dig in deeper.

**Comment by jneilliii** [comment]
Fix available with version 0.1.0rc7.
